# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: designmatch
  username: cdsierra1199
  password: HaroldCastro201601
  host: dbtest.c7adyf7ogphu.us-west-2.rds.amazonaws.com
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: designmatch
  username: cdsierra1199
  password: HaroldCastro201601
  host: dbtest.c7adyf7ogphu.us-west-2.rds.amazonaws.com
  port: 3306
