# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: DespliegueBDev
  username: jssalamanca1967
  password: contrasenia.27
  host: desplieguebdev.c16ip1pycpgj.us-west-2.rds.amazonaws.com
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: DespliegueBDev
  username: jssalamanca1967
  password: contrasenia.27
  host: desplieguebdev.c16ip1pycpgj.us-west-2.rds.amazonaws.com
  port: 3306
